Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
